[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/bingo084/nvim-config.git"
    refreshPeriod = "12h"
[".config/rime"]
    type = "git-repo"
    url = "https://github.com/bingo084/rime.git"
    refreshPeriod = "168h"
[".config/ags"]
    type = "git-repo"
    url = "https://github.com/bingo084/ags-config.git"
    refreshPeriod = "12h"
["bin"]
    type = "git-repo"
    url = "https://github.com/bingo084/script.git"
    refreshPeriod = "168h"
[".config/bat/themes"]
    type = "archive"
    url = "{{ .github }}/catppuccin/bat/archive/main.zip"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"
[".config/clash/config.yaml"]
    type = "file"
    url = {{ (rbwFields "Subscribe").MihomoConfig.value | quote }}
    refreshPeriod = "168h"
[".config/git/themes/catppuccin.gitconfig"]
    type = "file"
    url = "{{ .githubRaw }}/catppuccin/delta/main/catppuccin.gitconfig"
    refreshPeriod = "168h"
