[".config/zsh/plugins/fzf-zsh-completion.sh"]
    type = "file"
    url = "{{ .githubRaw }}/lincheney/fzf-tab-completion/master/zsh/fzf-zsh-completion.sh"
    refreshPeriod = "168h"
[".config/zsh/plugins/auto-notify.plugin.zsh"]
    type = "file"
    url = "{{ .githubRaw }}/MichaelAquilina/zsh-auto-notify/master/auto-notify.plugin.zsh"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/bingo084/nvim-config.git"
    refreshPeriod = "12h"
[".config/rime"]
    type = "git-repo"
    url = "https://github.com/bingo084/rime.git"
    refreshPeriod = "168h"
["bin"]
    type = "git-repo"
    url = "https://github.com/bingo084/script.git"
    refreshPeriod = "168h"
[".config/zsh/completions/_fzf"]
    type = "file"
    url = "{{ .githubRaw }}/lmburns/dotfiles/master/.config/zsh/completions/_fzf"
    refreshPeriod = "168h"
[".config/bat/themes"]
    type = "archive"
    url = "{{ .github }}/catppuccin/bat/archive/main.zip"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"
{{ $version := (gitHubLatestRelease "MetaCubeX/mihomo").TagName -}}
[".config/mihomo/mihomo"]
    type = "file"
    url = "{{ .github }}/MetaCubeX/mihomo/releases/download/{{ $version }}/mihomo-{{ .chezmoi.os }}-{{ .chezmoi.arch }}-{{ $version }}.gz"
    executable = true
    filter.command = "gzip"
    filter.args = ["-d"]
    refreshPeriod = "168h"
