[".config/zsh/plugins/fzf-zsh-completion.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/lincheney/fzf-tab-completion/master/zsh/fzf-zsh-completion.sh"
    refreshPeriod = "168h"
[".config/zsh/plugins/auto-notify.plugin.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/MichaelAquilina/zsh-auto-notify/master/auto-notify.plugin.zsh"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:bingo084/nvim-config.git"
    refreshPeriod = "168h"
["bin"]
    type = "git-repo"
    url = "git@github.com:bingo084/script.git"
    refreshPeriod = "168h"
[".config/rime"]
    type = "git-repo"
    url = "git@github.com:bingo084/rime.git"
    refreshPeriod = "168h"
["dwm"]
    type = "git-repo"
    url = "git@github.com:bingo084/dwm.git"
    refreshPeriod = "168h"
["dwmblocks"]
    type = "git-repo"
    url = "git@github.com:bingo084/dwmblocks.git"
    refreshPeriod = "168h"
[".config/zsh/completions/_fzf"]
    type = "file"
    url = "https://raw.githubusercontent.com/lmburns/dotfiles/master/.config/zsh/completions/_fzf"
    refreshPeriod = "168h"
[".config/bat/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/bat/archive/main.zip"
    stripComponents = 2
    include = ["*/themes/*"]
    refreshPeriod = "168h"
