[".config/fzf/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/bingo084/nvim-config.git"
    refreshPeriod = "168h"
