[".config/fzf/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/bingo084/nvim-config.git"
    refreshPeriod = "168h"
["bin"]
    type = "git-repo"
    url = "git@github.com:bingo084/script.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger_devicons"]
    type = "git-repo"
    url = "https://github.com/alexanderjeurissen/ranger_devicons.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/zoxide"]
    type = "git-repo"
    url = "https://github.com/jchook/ranger-zoxide.git"
    refreshPeriod = "168h"
[".config/rime"]
    type = "git-repo"
    url = "https://github.com/bingo084/rime.git"
    refreshPeriod = "168h"
