[".config/fzf/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:bingo084/nvim-config.git"
    refreshPeriod = "168h"
["bin"]
    type = "git-repo"
    url = "git@github.com:bingo084/script.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger_devicons"]
    type = "git-repo"
    url = "https://github.com/alexanderjeurissen/ranger_devicons.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/zoxide"]
    type = "git-repo"
    url = "https://github.com/jchook/ranger-zoxide.git"
    refreshPeriod = "168h"
[".config/rime"]
    type = "git-repo"
    url = "git@github.com:bingo084/rime.git"
    refreshPeriod = "168h"
["dwm"]
    type = "git-repo"
    url = "git@github.com:bingo084/dwm.git"
    refreshPeriod = "168h"
["dwmblocks"]
    type = "git-repo"
    url = "git@github.com:bingo084/dwmblocks.git"
    refreshPeriod = "168h"
[".config/zsh/completions/_fzf"]
    type = "file"
    url = "https://raw.githubusercontent.com/lmburns/dotfiles/master/.config/zsh/completions/_fzf"
    refreshPeriod = "168h"
[".config/bat/themes/Catppuccin-frappe.tmTheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-frappe.tmTheme"
    refreshPeriod = "168h"
[".config/bat/themes/Catppuccin-latte.tmTheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-latte.tmTheme"
    refreshPeriod = "168h"
[".config/bat/themes/Catppuccin-macchiato.tmTheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-macchiato.tmTheme"
    refreshPeriod = "168h"
[".config/bat/themes/Catppuccin-mocha.tmTheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-mocha.tmTheme"
    refreshPeriod = "168h"
