keypress_delay_ms: 20
modmap:
  - name: HHKB
    remap:
      capslock:
        held: leftctrl
        alone: esc
        alone_timeout_millis: 1000
      leftmeta: leftalt
      leftalt: leftmeta
      esc: grave
      grave: esc
      backspace: backslash
      backslash: backspace
    device:
      only: ["AT Translated Set 2 keyboard"]
  - name: Smart Ctrl/Esc
    remap:
      leftctrl:
        held: leftctrl
        alone: esc
        alone_timeout_millis: 1000
  - name: Mouse key
    remap:
      btn_side:
        held: leftmeta
        alone: btn_side
      btn_extra:
        held: leftalt
        alone: btn_extra
keymap:
  - name: ChooseAll/Copy/Paste/Cut/Undo
    remap:
      SUPER-a: [C-home, C-a, { set_mark: true }]
      SUPER-c: [C-c, { set_mark: false }]
      SUPER-v: [C-v, { set_mark: false }]
      SUPER-x: [C-x, { set_mark: false }]
      SUPER-z: [C-z, { set_mark: false }]
      ESC: [ESC, { set_mark: false }]
    application:
      not: [kitty, wezterm, jetbrains-idea]
  - name: Browser
    remap:
      C-apostrophe: C-tab
      C-semicolon: C-SHIFT-tab
    application:
      only: [google-chrome, firefox]
  - name: Emacs
    remap:
      # Cursor
      C-b: { with_mark: left }
      C-f: { with_mark: right }
      C-p: { with_mark: up }
      C-n: { with_mark: down }
      # Forward/Backward word
      M-b: { with_mark: C-left }
      M-f: { with_mark: C-right }
      # Beginning/End of line
      C-a: { with_mark: home }
      C-e: { with_mark: end }
      # Page up/down
      # M-v: { with_mark: pageup }
      # C-v: { with_mark: pagedown }
      # Newline
      C-m: enter
      C-j: enter
      C-o: [enter, left]
      # Delete
      C-d: [delete, { set_mark: false }]
      M-d: [C-delete, { set_mark: false }]
      C-h: [backspace, { set_mark: false }]
      C-w: [C-backspace, { set_mark: false }]
      # Kill line
      C-k: [Shift-end, C-x, { set_mark: false }]
      C-u: [end, Shift-home, C-x, { set_mark: false }]
      # Search
      C-s: C-f
      # Cancel
      C-g: [esc, { set_mark: false }]
      C-x:
        remap:
          # C-x C-f (open)
          C-f: C-o
          # C-x C-s (save)
          C-s: C-s
          # C-x k (kill tab)
          k: C-f4
          # C-x C-c (exit)
          C-c: C-q
    application:
      not: [kitty, wezterm, /jetbrains-*/]
