require("monitors")

require("modules.animations")
require("modules.appearance")
require("modules.autostart")
require("modules.binds")
require("modules.env")
require("modules.gestures")
require("modules.input")
require("modules.layouts")
require("modules.misc")
require("modules.plugins")
require("modules.rules")
