"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = ["C"], run = "plugin ouch --args=zip", desc = "Compress with ouch" },
  { on = ["R"], run = "rename", desc = "Rename a file or directory" },
  { on = ["u"], run = "plugin restore", desc = "Restore last deleted files/folders" },
]

[tasks]

prepend_keymap = [
  { on = "q", run = "close", desc = "Close task manager" },
  { on = ["d", "d"], run = "cancel", desc = "Cancel the task" },
]

[spot]

prepend_keymap = [{ on = "q", run = "close", desc = "Close spot" }]

[completion]

prepend_keymap = [
  { on = ["<C-e>"], run = "close", desc = "Cancel completion" },
  { on = ["<C-y>"], run = "close --submit", desc = "Submit the completion" },
]

[help]

prepend_keymap = [
  { on = ["u"], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = ["d"], run = "arrow 5", desc = "Move cursor down 5 lines" },
  { on = ["<C-u>"], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = ["<C-d>"], run = "arrow 5", desc = "Move cursor down 5 lines" },
  { on = "q", run = "close", desc = "Close help" },
]
