#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio = [1, 2, 3]
sort_by = "natural"

[preview]
max_width = 1200
max_height = 1800

[plugin]
prepend_previewers = [
  # Archive previewer
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch" },
]
prepend_fetchers = [
  { url = "*", run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" },
]
