#!/bin/sh

switch_monitor() {
	monitor_count=$(hyprctl monitors -j | jq '. | length')
	activeworkspace=$(hyprctl activeworkspace -j | jq '.id')

	if [ "$monitor_count" -gt 1 ]; then
		echo "More than one monitor detected, disabling eDP-1..."
		hyprctl keyword monitor eDP-1, disable
		hyprctl dispatch workspace $activeworkspace
	elif [ "$monitor_count" -eq 0 ]; then
		echo "Only one monitor detected, enabling eDP-1..."
		hyprctl keyword monitor eDP-1, preferred, auto, 1
		hyprctl dispatch workspace $activeworkspace
	fi
}

handle() {
	case $1 in
	monitoradded* | monitorremoved*)
		echo "$1" | grep -q "eDP-1" && return
		echo "Monitor added or removed, checking monitor status..."
    switch_monitor
		;;
	esac
}

if [ "$1" = "-d" ]; then
    echo "Listening for monitor events with socat..."
    switch_monitor
    socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
else
    switch_monitor
fi
