#!/bin/bash
interval="$1"
image_url="https://bing.biturl.top/?resolution=3840&format=image&index=random&mkt=random"
image_path="$HOME/.cache/wallpaper.jpg"

update_wal() {
  # Download wallpaper
  curl -sL -o $image_path $image_url

  matugen image $image_path
}

if [ -n "$interval" ]; then
  while true; do
    update_wal
    sleep "$interval"
  done
else
  update_wal
fi
