#!/bin/sh

ensure_one_monitor_on() {
	monitor_count=$(hyprctl monitors -j | jq '. | length')
	if [ "$monitor_count" -eq 0 ]; then
		echo "Only one monitor detected, enabling eDP-1..."
		hyprctl keyword monitor eDP-1, preferred, auto, 1
	fi
}

handle() {
	case $1 in
	monitoraddedv2* | monitorremoved*)
		echo "Monitor added or removed, checking monitor status..."
		ensure_one_monitor_on
		;;
	esac
}

if [ "$1" = "-d" ]; then
	echo "Listening for monitor events with socat..."
	ensure_one_monitor_on
	socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
else
	ensure_one_monitor_on
fi
