#!/bin/sh

switch_monitor() {
	monitor_count=$(hyprctl monitors -j | jq '. | length')
	if [ "$monitor_count" -gt 1 ]; then
		echo "More than one monitor detected, disabling eDP-1..."
		hyprctl keyword monitor eDP-1, disable
	elif [ "$monitor_count" -eq 0 ]; then
		echo "Only one monitor detected, enabling eDP-1..."
		hyprctl keyword monitor eDP-1, preferred, auto, 1
	fi
	hyprctl dispatch workspace 1
}

handle() {
	case $1 in
	monitoraddedv2* | monitorremoved*)
		echo "$1" | grep -q -e "eDP-1" -e "FALLBACK" && return
		echo "Monitor added or removed, checking monitor status..."
		switch_monitor
		;;
	esac
}

if [ "$1" = "-d" ]; then
	echo "Listening for monitor events with socat..."
	switch_monitor
	socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
else
	switch_monitor
fi
