[packages]
arch = [
  # Browser
  "google-chrome",
  { name = "firefox", deps = "firefox-i18n-zh-cn" },
  # Communication
  "linuxqq",
  "telegram-desktop",
  # Desktop
  "android-tools",          # ADB command (adb, fastboot, etc.)
  "android-udev",           # Mount device
  "blueman",                # Bluetooth
  "breeze-cursors",
  "brightnessctl",
  "cliphist",               # Clipboard history
  "ddcutil",                # External monitor brightness
  "dunst",                  # Notification
  "gnome-keyring",          # Stores passwords and encryption keys
  "matugen-bin",            # Material you color generation tool
  "mission-center",         # System monitor
  "network-manager-applet", # Network
  "polkit-kde-agent",       # Authentication agent
  "power-profiles-daemon",  # Power management
  "rofi",                   # App launcher
  "sddm",                   # Login manager
  "swaylock-effects",       # Lock screen
  "swww",                   # Wallpaper
  "udiskie",                # Automatically mounting
  "wtype",                  # Simulate paste shortcuts
  "xremap-wlroots-bin",
  # Driver
  "libva-utils", # Intel VA-API Media Applications and Scripts for libva
  { name = "intel-ucode", when = "intel-cpu" },
  { name = "mesa", when = "intel-gpu", packages = [ # Open-source OpenGL drivers
    "intel-media-driver", # VA-API
    "vulkan-intel",       # Open-source Vulkan driver for Intel GPUs
  ] },
  { name = "nvidia-open-dkms", when = "nvidia", deps = [
    "libva-nvidia-driver", # VA-API implementation that uses NVDEC as a backend
    "linux-headers",
    "nvidia-prime",
    "nvidia-settings",     # Tool for configuring the NVIDIA graphics driver
  ] },
  # File manager
  "gvfs-mtp", # MTP support for file managers
  "nautilus",
  { name = "yazi", deps = [
    "7zip",                # Archive extraction and preview
    "fd",                  # File search
    "ffmpegthumbnailer",   # Video thumbnails
    "fzf",                 # Directory jumping
    "imagemagick",         # SVG, Font, HEIC, and JPEG XL preview
    "jq",                  # JSON preview
    "ouch",                # Yazi plugin preview archives
    "perl-image-exiftool", # Metadata preview
    "poppler",             # PDF preview
    "ripgrep",             # File content search
    "zoxide",              # Directory jumping
  ] },
  # Fonts
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "noto-fonts-extra",
  "ttf-droid",
  "ttf-jetbrains-mono-nerd",
  # Input method
  { name = "fcitx5", deps = [
    "fcitx5-configtool",
    "fcitx5-gtk",
    "fcitx5-qt",
    "fcitx5-rime",
    "fcitx5-skin-fluentdark-git",
    "fcitx5-skin-fluentlight-git",
    "rime-emoji",
    "rime-sbxlm",
  ] },
  # Language
  "go",
  "npm",
  "rust",
  # Media player
  "mpv",
  { name = "clapper", deps = [
    "gst-libav",     # Extra media decoders (via FFmpeg)
    "gst-plugin-va", # Hardware-accelerated video decode (via VA-API)
    # Extra media decoders
    "gst-plugins-bad",
    "gst-plugins-base",
    "gst-plugins-ugly",
  ] },
  # Package manager
  "base-devel",     # Basic tools to build Arch Linux packages
  "chezmoi",
  "pacman-contrib", # Contributed scripts and tools for pacman systems (pactree, checkupdates, etc.)
  "paru",
  "pkgstats",
  # Sound
  "pavucontrol",    # Simple GTK volume control tool ("mixer") for PulseAudio.
  "pipewire-alsa",  # Low-latency audio/video router and processor - ALSA configuration
  "pipewire-audio", # Low-latency audio/video router and processor - Audio support
  "pipewire-pulse", # Low-latency audio/video router and processor - PulseAudio replacement
  "sof-firmware",   # Sound Open Firmware
  # Status bar
  { name = "aylurs-gtk-shell", deps = [
    "dart-sass",        # Compile scss
    "libastal-meta",    # Library for astal
    "libgtop",          # Library for collecting system monitoring data
    "otf-font-awesome", # Bar icons
  ] },
  # Terminal
  "atuin",
  "bat",
  "btop",
  "dust",                                        # A more intuitive version of du in rust
  "eza",
  "fzf",
  "fzf-tab-git",
  "gemini-cli",
  "git",
  "git-delta",
  "hugo",
  "kitty",
  "lazygit",
  "man-db",
  "mihomo",
  "ntfysh-bin",
  "openai-codex",
  "opencode",
  "python-pywal",
  "starship",
  "tldr",
  "trash-cli",
  "unzip",
  "zoxide",
  "zsh",
  { name = "neovim", deps = "tree-sitter-cli" },
  # Window manager
  { name = "hyprland", deps = [
    "hdrop-git",
    "hypridle",
    "hyprland-scratchpad-git",
    "hyprlock",
    "hyprpicker",
    "hyprshot",
    "kanshi",                      # Output management
    "satty",                       # Screenshot annotation tool
    "scdoc",                       # Build hdrop documentation
    "socat",                       # Monitor hyprland sock
    "xdg-desktop-portal-hyprland",
  ] },
  { name = "niri", deps = [
    "gnome-keyring",
    "polkit-kde-agent",
    "xdg-desktop-portal-gnome",
    "xdg-desktop-portal-gtk",
    "xwayland-satellite",
  ] },
]
