[packages]
arch = [
  { group = "Package manager", packages = [
    "base-devel",     # 	Basic tools to build Arch Linux packages
    "chezmoi",
    "pacman-contrib", # Contributed scripts and tools for pacman systems (pactree, checkupdates, etc.)
    "paru",
    "pkgstats",
  ] },

  { group = "Android", packages = [
    "android-tools", # ADB command (adb, fastboot, etc.)
    "android-udev",  # Mount device
  ] },
  { group = "Desktop environment", packages = [
    "blueman", # Bluetooth
    "cliphist", # Clipboard history
    "dunst", # Notification
    "gnome-keyring", # Stores passwords and encryption keys
    "mission-center",
    "mpv",
    "network-manager-applet", # Network
    "polkit-kde-agent", # Authentication agent
    "rofi-wayland", # App launcher
    "sddm", # Login manager
    "swaylock-effects", # Lock screen
    "swww", # Wallpaper
    "telegram-desktop",
    "udiskie", # Automatically mounting
    "wlogout", # Logout menu
    "wtype", # Simulate paste shortcuts
    { group = "Brightness", packages = [
      "brightnessctl",
      "ddcutil",       # External monitor brightness
    ] },
    { group = "Browser", packages = [
      "firefox",
      { name = "google-chrome", aur = true },
    ] },
    { group = "File manager", packages = [
      "gvfs-mtp",
      "nautilus", # File manager
      "vsftpd", # FTP
      { group = "Yazi", deps = true, packages = [
        "7zip",                                         # Archive extraction and preview
        "fd",                                           # File serach
        "ffmpegthumbnailer",                            # Video thumbnails
        "fzf",                                          # Directory jumping
        "imagemagick",                                  # SVG, Font, HEIC, and JPEG XL preview
        "jq",                                           # JSON preview
        "poppler",                                      # PDF preview
        "ripgrep",                                      # File content search
        "zoxide",                                       # Directory jumping
        { name = "ouch", deps = false },                # Yazi plugin preview archives
        { name = "perl-image-exiftool", deps = false }, # Metadata preview
        { name = "yazi", deps = false },
      ] },
    ] },
    { group = "Hyprland", packages = [
      "hypridle",
      "hyprland",
      "hyprlock",
      "satty",                              # Screenshot annotation tool
      "socat",                              # Monitor hyprland sock
      "xdg-desktop-portal-hyprland",
      { name = "hyprpicker", deps = true },
      { name = "hyprshot", aur = true },
    ] },
    { group = "Input method", packages = [
      "fcitx5",
      "fcitx5-configtool",
      "fcitx5-gtk",
      "fcitx5-qt",
      "fcitx5-rime",
      "rime-double-pinyin",
      "rime-emoji",
      { name = "fcitx5-skin-fluentlight-git", aur = true },
    ] },
    { group = "Media Player", packages = [
      "clapper",
      { name = "gst-libav", deps = true },     # Extra media decoders (via FFmpeg)
      { name = "gst-plugin-va", deps = true }, # Hardware-accelerated video decode (via VA-API)
      # Extra media decoders
      { name = "gst-plugins-bad", deps = true },
      { name = "gst-plugins-base", deps = true },
      { name = "gst-plugins-ugly", deps = true },
    ] },
    { group = "Sound", packages = [
      "alsa-utils",     # Advanced Linux Sound Architecture - Utilities
      "pavucontrol",    # Simple GTK volume control tool ("mixer") for PulseAudio.
      "pipewire-alsa",  # Low-latency audio/video router and processor - ALSA configuration
      "pipewire-audio", # Low-latency audio/video router and processor - Audio support
      "pipewire-pulse", # Low-latency audio/video router and processor - PulseAudio replacement
      "sof-firmware",   # Sound Open Firmware
    ] },
    { group = "Status Bar", packages = [
      { name = "aylurs-gtk-shell", aur = true },  # AGS
      { name = "libgtop", deps = true },          # Library for collecting system monitoring data
      { name = "otf-font-awesome", deps = true }, # Bar icons
    ] },
    { name = "linuxqq", aur = true },
    { name = "xremap-wlroots-bin", aur = true },
  ] },
  { group = "Driver", packages = [
    { group = "Intel", packages = [
      "intel-media-driver", # VA-API
      "intel-ucode",
      "libva-utils",        # Intel VA-API Media Applications and Scripts for libva
      "mesa",               # Open-source OpenGL drivers
      "vulkan-intel",       # Open-source Vulkan driver for Intel GPUs
    ] },
    { group = "Nvidia", packages = [
      "libva-nvidia-driver",                   # VA-API implementation that uses NVDEC as a backend
      "nvidia-open-dkms",
      "nvidia-prime",
      "nvidia-settings",                       # Tool for configuring the NVIDIA graphics driver
      { name = "linux-headers", deps = true },
    ] },
  ] },
  { group = "Fonts", packages = [
    "noto-fonts-cjk",
    "noto-fonts-emoji",
    "noto-fonts-extra",
    "ttf-droid",
    "ttf-jetbrains-mono-nerd",
  ] },
  { group = "Language", packages = [
    "go",
    "npm",
    "rust",
  ] },
  { group = "Terminal", packages = [
    "atuin",
    "bat",
    "btop",
    "clash-meta",
    "dust",                              # A more intuitive version of du in rust
    "eza",
    "fzf",
    "fzf-tab-git",
    "git",
    "git-delta",
    "hugo",
    "kitty",
    "man-db",
    "neovim",
    "python-pywal",
    "starship",
    "tldr",
    "trash-cli",
    "unzip",
    "zoxide",
    "zsh",
    { name = "ntfysh-bin", aur = true },
  ] },
]
